// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package trade_service

import (
	"bytes"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const EX_INTERNAL_ERROR = "trader internal error"
const EX_PRICE_OUT_OF_SCOPE = "price is out of scope"
const EX_NO_USABLE_FUND = "no usable exchange fund  by now"
const EX_NO_USABLE_DEPTH = "no usable exchange depth by now"
const EX_TRADE_QUEUE_FULL = "trade queue is full"
const EX_DEPTH_INSUFFICIENT = "exchange depth is insufficient"
const EX_PRICE_NOT_SYNC = "price is not in tickers"
const EX_EXIST_ERROR_ORDERS = "exist error status orders"

func init() {
}
