// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "github.com/apache/thrift/lib/go/thrift"
        "trade_service"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  void ping()")
  fmt.Fprintln(os.Stderr, "  void config_keys( exchange_configs)")
  fmt.Fprintln(os.Stderr, "  void config_amount(AmountConfig amount_config)")
  fmt.Fprintln(os.Stderr, "  ExchangeStatus get_exchange_status()")
  fmt.Fprintln(os.Stderr, "  void check_price(double price, TradeType trade_type)")
  fmt.Fprintln(os.Stderr, "  void buy(Trade trade)")
  fmt.Fprintln(os.Stderr, "  void sell(Trade trade)")
  fmt.Fprintln(os.Stderr, "  Ticker get_ticker()")
  fmt.Fprintln(os.Stderr, "   get_account()")
  fmt.Fprintln(os.Stderr, "  void get_alert_orders()")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    parsedUrl, err := url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  client := trade_service.NewTradeServiceClientFactory(trans, protocolFactory)
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "ping":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "Ping requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.Ping())
    fmt.Print("\n")
    break
  case "config_keys":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ConfigKeys requires 1 args")
      flag.Usage()
    }
    arg18 := flag.Arg(1)
    mbTrans19 := thrift.NewTMemoryBufferLen(len(arg18))
    defer mbTrans19.Close()
    _, err20 := mbTrans19.WriteString(arg18)
    if err20 != nil { 
      Usage()
      return
    }
    factory21 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt22 := factory21.GetProtocol(mbTrans19)
    containerStruct0 := trade_service.NewTradeServiceConfigKeysArgs()
    err23 := containerStruct0.ReadField1(jsProt22)
    if err23 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.ExchangeConfigs
    value0 := argvalue0
    fmt.Print(client.ConfigKeys(value0))
    fmt.Print("\n")
    break
  case "config_amount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ConfigAmount requires 1 args")
      flag.Usage()
    }
    arg24 := flag.Arg(1)
    mbTrans25 := thrift.NewTMemoryBufferLen(len(arg24))
    defer mbTrans25.Close()
    _, err26 := mbTrans25.WriteString(arg24)
    if err26 != nil {
      Usage()
      return
    }
    factory27 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt28 := factory27.GetProtocol(mbTrans25)
    argvalue0 := trade_service.NewAmountConfig()
    err29 := argvalue0.Read(jsProt28)
    if err29 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.ConfigAmount(value0))
    fmt.Print("\n")
    break
  case "get_exchange_status":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetExchangeStatus requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetExchangeStatus())
    fmt.Print("\n")
    break
  case "check_price":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "CheckPrice requires 2 args")
      flag.Usage()
    }
    argvalue0, err30 := (strconv.ParseFloat(flag.Arg(1), 64))
    if err30 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    tmp1, err := (strconv.Atoi(flag.Arg(2)))
    if err != nil {
      Usage()
     return
    }
    argvalue1 := trade_service.TradeType(tmp1)
    value1 := argvalue1
    fmt.Print(client.CheckPrice(value0, value1))
    fmt.Print("\n")
    break
  case "buy":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Buy requires 1 args")
      flag.Usage()
    }
    arg31 := flag.Arg(1)
    mbTrans32 := thrift.NewTMemoryBufferLen(len(arg31))
    defer mbTrans32.Close()
    _, err33 := mbTrans32.WriteString(arg31)
    if err33 != nil {
      Usage()
      return
    }
    factory34 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt35 := factory34.GetProtocol(mbTrans32)
    argvalue0 := trade_service.NewTrade()
    err36 := argvalue0.Read(jsProt35)
    if err36 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.Buy(value0))
    fmt.Print("\n")
    break
  case "sell":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Sell requires 1 args")
      flag.Usage()
    }
    arg37 := flag.Arg(1)
    mbTrans38 := thrift.NewTMemoryBufferLen(len(arg37))
    defer mbTrans38.Close()
    _, err39 := mbTrans38.WriteString(arg37)
    if err39 != nil {
      Usage()
      return
    }
    factory40 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt41 := factory40.GetProtocol(mbTrans38)
    argvalue0 := trade_service.NewTrade()
    err42 := argvalue0.Read(jsProt41)
    if err42 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.Sell(value0))
    fmt.Print("\n")
    break
  case "get_ticker":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetTicker requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetTicker())
    fmt.Print("\n")
    break
  case "get_account":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetAccount requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetAccount())
    fmt.Print("\n")
    break
  case "get_alert_orders":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetAlertOrders requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetAlertOrders())
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
